rbac:
  roles:
  - name: admin
    description: Role Admin
    permissions:
    - method: cli
      resources:
      - hello
      - world
  groups:
  - name: admin
    roles:
    - admin
    users:
    - nobody