name: ci-python-unittest
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements.txt
    
    - name: Run tests
      run: |
        python -m unittest rbac/tests/test_rbac.py -vvv